name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Runs on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm install
          npm run build
          cp dist/index.html dist/404.html  # Fix Vue Router on GitHub Pages

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
